### ISSUE TITLE
Plot3: heatmap of prices with Map interactivity

### ISSUE THREAD

**Issue by Affrin101** [UBC-MDS/Cost_of_living_py#18]

**Comment by Affrin101** [comment]
Hi Folks, I have made this map wherein the size of the points depends on the cost column `all` and color is as per the `region`. This may be just a preliminary plot and might need changes but before proceeding any further I wanted to show you guys and get to know if we are moving in the right direction or not? I have also added a tooltip that shows the name of the city, country, all prices, and region. I had to do some wrangling and I have added two new columns latitude and longitude to the CSV file so as to link it to world data of vega-dataset . Attaching the new csv file as well.

Please have a look and give me your feedback on the same and let me know if anything else is needed
[processed_data1.csv](https://github.com/UBC-MDS/Cost_of_living_py/files/8181251/processed_data1.csv)

![visualization (1)](https://user-images.githubusercontent.com/51941766/156654664-d01ca7f2-2b19-464a-9bb3-8da835ae388c.png)

**Comment by Arushi282** [comment]
Hi @Affrin101, yeah I think we are definitely going in the right direction and great work so far! My only suggestion is if we color based on country as opposed to region, I think from the users perspective it would make more sense, but again not sure how feasible that is given the number of countries we have. @voremargot @hjw0703 what do you guys think?

**Comment by Affrin101** [comment]
Hi @Arushi282, thank you for the feedback, the change to color these points based on the country is not that big and I had it earlier but my concern was that in the European region there are too many cities and countries and the plot looks a bit cluttered and is not much interpretable. Actually it looks similar to the earlier plot but in the legend, there are too many options. PFB the screenshot of the plot as well.

![visualization (2)](https://user-images.githubusercontent.com/51941766/156658962-0fcdf2d8-f82b-4c51-b3eb-29e981605f3f.png)

**Comment by hjw0703** [comment]
Thank you for your hard work @Affrin101 ! Personally I think color based on region seems be more clear as opposed to country, you can just keep it like this.

**Comment by Arushi282** [comment]
Yeah agree, on looking at the color based on countries, I feel like there is a lot overlap between points, defeating the purposed of making clear plots. Let's stick with regions, thank you again!

**Comment by voremargot** [comment]
@Affrin101  I agree that the regions make more sense than the countries. One thing I think that you should do is have a different size chart title (something more descriptive than all) and make the sizes of the circles more different! Right now it is pretty hard to tell the difference between different sizes once they are on the map! Also is there functionality that will only show the countries that the user selects? This would make the map more specific to what the user is interested in.

**Comment by Affrin101** [comment]
@voremargot I ll work on the size chart title and see how it can be customized and also try adding interactivity based on country
