### ISSUE TITLE
Description and sketch

### ISSUE THREAD

**Issue by voremargot** [UBC-MDS/Cost_of_living_py#2]
This thread is for questions and comments about the outline for the dashboard

**Comment by voremargot** [comment]
[Initial Dashboard Sketch](https://github.com/UBC-MDS/Cost_of_living_py/blob/dashboard_planning/img/dashboard_design.pdf)

Please take a look at my initial sketch of the dash board. All red boxes will be drop down menus and the green box will allow the user to put in their expected salary so they can see their monthly surplus/deficit in a given city (the default for this could be the average salary of the city).  I didn't want the dashboard to become too overwhelming to look at so I left out the price of owning a vehicle in the city. Other small things we could add include a map showing where the cities are or a table to total cost of living for each city. Thoughts and opinions? Anything you think I should add or change? 
@Affrin101 @Arushi282 @hjw0703

**Comment by Affrin101** [comment]
@voremargot Great work on the Dashboard sketch!! Do you think we should also add another dropdown as country and based on the selected country only the cities in that country will be visible in the dropdown?  I think the idea about including a map to show the cities sounds great, may be we can also add heatmaps to the map to show cities and  the intensity of color varying with decreasing cost of living ?  Your Thoughts and opinions? @voremargot @Arushi282 @hjw0703

**Comment by voremargot** [comment]
Ohhh I like the heat map intensity of cost of living on a map! I was thinking about a country drop down menu but then I was wondering if region was better. There are a lot of small eastern European countries that only have 1 city and it might be nice to do it by larger regions. We can have large countries like USA, Canada, and Russia, and group other countries by region such as eastern europe, south america, ect. I am easy either way though!

**Comment by Arushi282** [comment]
Hi @voremargot, yes definitely a great initial sketch, below I have provided some suggestions:

(1) I think it would be a good idea to provide some descriptions on some of the buttons in our dash board, this could be in the form of text-boxes on the side with an arrow pointing to the button, it would make it easier to see to see the flow of the dashboard. 

(2) Following up on the above discussion by @Affrin101 and @voremargot , I definitely love the idea of heat map on a world map, but if we do that then it would be better to have it by regions just to make things simple and give a high level visualization to our users. I think we should stick to either classifying cities based on regions or countries but not both as it can get confusing.

**Comment by voremargot** [comment]
Here is a new draft! 
https://github.com/UBC-MDS/Cost_of_living_py/blob/dashboard_planning/img/dashboard_design_draft2.pdf

I have added in a heat map as well as added some commentary about what different drop down menus do
